#!/usr/bin/env bash
set -euo pipefail

# Script to display field configuration guide for the project
# Shows how Status and Dependency Status fields work together

OWNER="o2alexanderfedin"
PROJECT_NUMBER=12

echo "📋 GitHub Project Field Configuration Guide"
echo "=========================================="
echo ""
echo "This project uses a streamlined field configuration where:"
echo ""
echo "🔄 **Status Field** (Built-in)"
echo "   - Todo: Work not started"
echo "   - In Progress: Currently being worked on"
echo "   - Done: Work completed"
echo ""
echo "🔗 **Dependency Status Field** (Custom)"
echo "   - Ready: All dependencies satisfied, can start work"
echo "   - Blocked: Waiting on other work to complete"
echo "   - Partial: Some dependencies met, prep work possible"
echo "   - Unknown: Dependencies not yet analyzed"
echo ""
echo "💡 **How They Work Together:**"
echo "================================"
echo ""
echo "1. **Sprint Planning**: Filter by 'Dependency Status = Ready' to find work that can start"
echo "2. **Work Begins**: When starting work, update 'Status' to 'In Progress'"
echo "3. **Blocked Work**: If work gets blocked, keep 'Status' as is, update 'Dependency Status' to 'Blocked'"
echo "4. **Completion**: When work finishes, update 'Status' to 'Done'"
echo "5. **Unblocking**: When dependencies complete, update blocked items to 'Dependency Status = Ready'"
echo ""
echo "📊 **Example Workflow:**"
echo "======================"
echo ""
echo "New Task Created:"
echo "  Status: Todo"
echo "  Dependency Status: Blocked (waiting on foundation work)"
echo ""
echo "Dependencies Complete:"
echo "  Status: Todo"
echo "  Dependency Status: Ready ← Can now be added to sprint"
echo ""
echo "Work Starts:"
echo "  Status: In Progress ← Developer begins work"
echo "  Dependency Status: Ready"
echo ""
echo "Work Completes:"
echo "  Status: Done ← Task finished"
echo "  Dependency Status: Ready"
echo ""
echo "🚀 **Sprint Planning Views:**"
echo "============================"
echo ""
echo "Ready for Sprint:"
echo "  Filter: Dependency Status = 'Ready' AND Status = 'Todo'"
echo ""
echo "Blocked Work:"
echo "  Filter: Dependency Status = 'Blocked'"
echo ""
echo "In Progress:"
echo "  Filter: Status = 'In Progress'"
echo ""
echo "Critical Path:"
echo "  Filter: Dependency Risk = 'Critical'"
echo ""
echo "📈 **Benefits of This Approach:**"
echo "================================"
echo "✅ No redundancy between fields"
echo "✅ Clear separation of workflow state vs dependency state"
echo "✅ Easy to identify work ready for sprint planning"
echo "✅ Built-in field for basic Kanban, custom fields for advanced planning"
echo ""